### ISSUE TITLE
Brainstorming

### ISSUE THREAD

**Issue by on3iro** [on3iro/BGAchievements#1]
# Web application for user generated board game achievements
## Basic features
* Register User
* Create Profile
* Add games to collection (maybe list games via BGG API?)
* Add achievements / achievementlist to game
* Achievement:
    * Icon
    * Name
    * Requirements

## Additional features
* PWA?
* "official" achievements (e.g. for games like gloomhaven)
* share achievements
* Share Achievement-Lists
* Rate achievement lists
* Browse highest rated achievements / achievement lists
* Track game stats (times played, times won, points etc.)

**Comment by Thoryk** [comment]
Thoughts while kebap:

Define requirements per achievement, for example counter 500 with title "kill goblins". On the overview page for the board game a UI element appears with a + icon where you can add goblin kills. When the amount has been reached a notification appears, that you reached an achievement.

Another example: clear dungeon A, B and C to for the achievement "dungeon master". Board game overview page:

- [ ] dungeon A
- [ ] dungeon B
- [ ] dungeon C

When all dungeons are checked the notification appears, or maybe the achievement directly.

**Comment by on3iro** [comment]
Task-Tracking in general is a great idea. I think we should first nail the base implementation, though.
We should develop a roadmap for the whole project and add  this feature as well.
