### ISSUE TITLE
Create discord-server and a fancy README badge =)

### ISSUE THREAD

**Issue by on3iro** [on3iro/BGAchievements#17]
We could also use Slack if you would prefer this.

@Thoryk @jannydiamond @pailipaili what do you think?

**Comment by on3iro** [comment]
ok, looks like we are going to use slack...

**Comment by jannydiamond** [comment]
@on3iro I'm okay with both :)

**Comment by on3iro** [comment]
slack it is. I will set up the server tomorrow

**Comment by on3iro** [comment]
Okay,
I created a basic slack server. Didn't set it up properly, though.
One thing that currently really bugs me, is that joining a slack server without an invitation or a whitelisted email-domain is not possible. This essentially means that we need to invite people to join us.

One thing i really like about discord is how open it is for other users.
@jannydiamond i've sent you an invitation to the server. Can you invite @pailipaili ?
@Thoryk which email address should I use to invite you? (you can send me a telegram if you don't want to make it publicly available here)

**Comment by jannydiamond** [comment]
@on3iro You can create an invitation-link for the channel and post it in our telegram group. So @Thoryk and @pailipaili can join.

**Comment by jannydiamond** [comment]
But we can also switch to Discord. I have no problem with that :)
