### ISSUE TITLE
Add 'work in progress disclaimer' to top of README

### ISSUE THREAD

**Issue by on3iro** [on3iro/BGAchievements#20]

**Comment by deenadrien** [comment]
Hello @on3iro  , I'm beginner and I would like to contribute for my first time.

Can I claim this issue ?

**Comment by on3iro** [comment]
Hey @deenadrien sure thing - glad you are interested in contributing.
Just send me a pull request.
Be aware that this project is currently just starting out, though (hence the disclaimer).

Our current goal is to build a working MVP (minimum valuable product) till summer.

**Comment by on3iro** [comment]
Oh and If you need any help - just let me know :)

**Comment by deenadrien** [comment]
Ok thanks, I try to do that for my first time 😄

**Comment by deenadrien** [comment]
I send you a pull request, I think it's OK 😄

**Comment by on3iro** [comment]
@deenadrien merged :)

Thanks for your effort.
I hope to get some stuff done on this project on the upcoming saturday.
We still need to work on the baseline, but I am pretty sure there will appear more opportunities to contribute in the future ;)

Unfortunately this is just a side project we are working on in our spare time. So we can't commit to it as much as we would like to.

**Comment by deenadrien** [comment]
Thanks for your trust ! 😄 

Good luck to you for this project ! 😄
