### ISSUE TITLE
Add MIT LICENSE.md

### ISSUE THREAD

**Issue by on3iro** [on3iro/BGAchievements#21]

**Comment by deenadrien** [comment]
Hello @cg-cnu , I'm beginner and I would like to contribute for my first time.

Are you asking to create a license.md with MIT license ?

**Comment by deenadrien** [comment]
Hello @on3iro  , I'm beginner and I would like to contribute for my first time.

Are you asking to create a license.md file with MIT license ?

**Comment by on3iro** [comment]
@deenadrien yes, exactly. This issue is more of a reminder to myself, though and is not really meant for contribution.

To be honest I did not really expect other people (besides those already involved) to be interested in contributing this early in the development cycle 😄

**Comment by Exoleet** [comment]
Hello @on3iro,
If you want i can create the LICENSE.md for you. 
I have retrieve the MIT license from the Open Source Initiative [web site](https://opensource.org/licenses/MIT),i just need to know who is the copyright holder ?

**Comment by on3iro** [comment]
Hey @Exoleet 

thanks for your interest in contributing.
The license looks fine, so go ahead and just send in a pull request.

For now just use my name "Theo Salzmann"
I might change it in the future :)

Thanks again! 🎈

**Comment by Exoleet** [comment]
@on3iro , I have send a PR #26 , I think it's ok.
Thanks for your quickly answer.

**Comment by on3iro** [comment]
@Exoleet yup - looks good. I have merged your PR. Thanks again for your contribution 👍
