### ISSUE TITLE
slackin...

### ISSUE THREAD

**Issue by on3iro** [on3iro/BGAchievements#32]
we might need this https://github.com/rauchg/slackin

#17

**Comment by on3iro** [comment]
@Thoryk @jannydiamond @pailipaili Ok setting up a public slack looks like quite a hassle.

At this point we basically have two options:

1. We could just run with slack, use it in private mode for now and use slackin later on to open a few channels to the public
2. We could switch to discord

While slack looks like it is more tailored to the whole 'team based project management' thing, we can probably enjoy most of its goods on discord as well. As BGAchievements is made for gamers it would also fit thematically (if that matters at all) and quite a few gamers will probably already have a discord account they could use to communicate with us.

So we should probably ask ourselves what we want to achieve with the chat system.

For me personally its **a)** team and project communication, **b)** communication with possible external collaborators and users and **c)** chat-bot/github integration

Discord easily hits all the ✔️'s here.

**Comment by jannydiamond** [comment]
I have no problem with switching to discord. :)

**Comment by on3iro** [comment]
Another alternative would be [spectrum](https://spectrum.chat/styled-components)

**Comment by on3iro** [comment]
Hm, just wanted to checkout spectrum, but somehow the signin fails my. I am currently stuck in a redirect-loop. I think for now we should just fallback to discord and call it a day ;)

**Comment by on3iro** [comment]
@jannydiamond @Thoryk @pailipaili I have created a barebones discord server for now.

To join just click this link https://discord.gg/GXks6u
I will then provide you with moderator rights.

We  can later on decide what channels we might night etc.
I also replaced the slack badge inside the README, so I'll close this for now.
