### ISSUE TITLE
Provide build scripts

### ISSUE THREAD

**Issue by sarathas** [on3iro/BGAchievements#81]
Provide build scripts (.sh and .bat) to deploy and run the application (backend and frontend)

**Comment by on3iro** [comment]
I am not quite sure if we should use .sh and .bat scripts. Both are a bit too low level for my taste. And I don't think we should support development on win systems at all, so we can throw `.bat` out of the window. If you are developing on windows, use a vm - period. 
#98 will make the whole setup/running process a lot easier anyway. 

Feel free to re-open this issue if you disagree @sarathas
