### ISSUE TITLE
Create Mockups and rough Designs

### ISSUE THREAD

**Issue by on3iro** [on3iro/BGAchievements#9]

**Comment by jannydiamond** [comment]
I designed the first mockups of the app and uploaded them on Invision: [Link](https://invis.io/VUFWPHGTXAF). You can comment on the screens and click through them. I also added some clickpaths already (blue highlighed, when you click on a screen. Let me know if everything is working.

**Comment by on3iro** [comment]
@jannydiamond cool, thanks - I will have a look later on

**Comment by on3iro** [comment]
@jannydiamond is there a way to see those mockups without registering? I am really not that keen on adding another account to my already pretty long list if it is avoidable 😁

**Comment by jannydiamond** [comment]
@on3iro You need to get an account to comment on the screens and get updates if someone replyed. Invision also has a "taskboard" where we can track the status of the screens (in progress, in review, approved, etc). For that I just need to add you to the project. When we make the designs in Sketch, we can also get some CSS styles for development from Invision. But if you have another solution where we can discuss the screens, I'm open for that. :) Maybe also in a discord channel? Are there kinda like threads when you answer to a comment? I know its possible in Slack.

**Comment by on3iro** [comment]
Technically we can simply put those desings into this issue and comment here. What exactly do we need to be able to discuss them?

**Comment by on3iro** [comment]
lol nevermind - I confused your login with the actual invision login. I wont register for now - seeing those mockups and commenting here inside the issue is enough imo. We will probably discuss them in person anyway :smile:

**Comment by jannydiamond** [comment]
I will rework the mockups according to the [MVP stories](https://github.com/on3iro/BGAchievements/projects/1).

**Comment by jannydiamond** [comment]
I updated the mockup screens and the [Invision prototype](https://invis.io/VUFWPHGTXAF).

@on3iro @Thoryk @sarathas @pailipaili

**Comment by on3iro** [comment]
Not bad. @jannydiamond and my just had a talk in person, though. There's quite a lot to discuss about those screens. Maybe we can get a discord voice session up and running in the next few days. ...we also need a way to screenshare...

**Comment by on3iro** [comment]
... we should incorporate the link to the mockups into our README, i'll open a new issue and make this a todo. Therefore closing here...
